name: 'Black Code Format'
description: 'Format Python code using Black and provide PR comments with results'
author: 'Antonio González'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.x'
  black-version:
    description: 'Black version to use'
    required: false
    default: '23.12.0'
  black-args:
    description: 'Black arguments to use'
    required: false
    default: '--check --verbose'
  github-token:
    description: 'GitHub token for commenting on PRs'
    required: true
    default: ${{ github.token }}
  paths:
    description: 'Paths to check (space-separated). Example: "src tests"'
    required: false
    default: '.'
  fail-on-error:
    description: 'Whether to fail the action if formatting issues are found'
    required: false
    default: 'true'

runs:
  using: 'node20'
  main: 'index.js'

branding:
  icon: 'code'
  color: 'black' 