name: Test Action
on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Create test files
        run: |
          mkdir -p test_files
          # test1.py - properly formatted
          cat > test_files/test1.py << 'EOF'
          def test_function():
              print("hello world")
          EOF
          
          # test2.py - intentionally poorly formatted
          cat > test_files/test2.py << 'EOF'
          def another_function( ):
              return     True
          EOF

      - name: Test with default settings
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          paths: 'test_files/test1.py'

      - name: Test with formatting issues
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          paths: 'test_files/test2.py'
          fail-on-error: 'false'

      - name: Test with different Python version
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          python-version: '3.11'
          black-version: '23.12.0'
          paths: 'test_files/test1.py'
