name: Test Action
on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Create test files
        run: |
          mkdir -p test_files
          echo "def test_function():" > test_files/test1.py
          echo "    print('hello world')" >> test_files/test1.py
          echo "def another_function( ):" > test_files/test2.py
          echo "    return     True" >> test_files/test2.py

      - name: Test with default settings
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test with custom paths
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          paths: 'test_files'
          fail-on-error: 'false'

      - name: Test with different Python version
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          python-version: '3.11'
          black-version: '23.12.0'